Use new authentication for Zabbix 6.4
lukecyca/pyzabbix pull request #207
Opened 2023-03-29 11:23 UTC by chrullrich

Zabbix 6.4 deprecates the "auth" JSON key. The auth token should be sent instead as an "Authorization: Bearer" header.

2023-03-29 12:20 UTC, chrullrich commented
Hm. The pre-commit thing is apparently a code style thing that wants to uglify a nested condition. I'd rather not follow that suggestion.

The failing tests are due, unsurprisingly, to the changed request payload. Changing line 222 to

    if not self.version or self.version < Version("6.4.0"):

will fix the tests, but then they will not test anything relevant anymore. Do you have a better idea?

2023-03-29 15:52 UTC, jooola requested changes
> The failing tests are due, unsurprisingly, to the changed request payload. Changing line 222 to
>
> if not self.version or self.version < Version("6.4.0"):
>
> will fix the tests, but then they will not test anything relevant anymore. Do you have a better idea?

I guess you'll have to fix the test, and add some more to test your addition.

2023-03-29 15:52 UTC, jooola commented on pyzabbix/api.py
> +        return request
Please move this out of the `AuthBase` class and put it next to the other version check condition.

I'd prefer having related things next to each other, and a auth class seem overkill for what we want to do.

2023-03-29 15:52 UTC, jooola commented on pyzabbix/api.py
> +            self.session.auth = ZabbixAPIAuth(self.auth)
Please make `Version("6.4.0")` a module constant.

2023-04-08 13:39 UTC, jooola approved these changes

2023-04-08 13:39 UTC, merged